import { createThemeScriptSource } from '@kvirn-ui/core'
import type { ThemeScriptOptions } from '@kvirn-ui/core'

export interface KvirnThemeScriptProps {
  /** The CSP nonce for this response, for a strict `script-src`. */
  nonce?: string | undefined
  /** The same object as `KvirnProvider theme`; only the three defaults are read. */
  theme?: ThemeScriptOptions | undefined
}

/**
 * The server-component version of `KvirnThemeScript` (same output): a blocking inline script for
 * `<head>` that sets the `data-kv-*` theme attributes on `<html>` before first paint. It has no
 * hook and ships no client JS. Put `suppressHydrationWarning` on `<html>`.
 */
export function KvirnThemeScript({ nonce, theme }: KvirnThemeScriptProps) {
  const source = createThemeScriptSource({
    defaultColorScheme: theme?.defaultColorScheme,
    defaultContrast: theme?.defaultContrast,
    defaultMotion: theme?.defaultMotion,
  })
  // The source is generated by core from constants and validated enums, never from input.
  return <script nonce={nonce} dangerouslySetInnerHTML={{ __html: source }} />
}
KvirnThemeScript.displayName = 'KvirnThemeScript'
