import { defineExampleTexts } from '../../components/local-example-texts.ts'

export const useDialogTexts = defineExampleTexts({
  en: {
    about: 'About the service',
    aboutTitle: 'About the service',
    aboutText: 'The service is run by the municipality and is open around the clock.',
    close: 'Close',
    changePhone: 'Change phone number',
    changePhoneTitle: 'Change phone number',
    changePhoneText: 'We send a code by text message to confirm the new number.',
    phoneNumber: 'Phone number',
    save: 'Save number',
    keep: 'Keep the old number',
    stateOpen: 'Open',
    stateClosed: 'Closed',
    lastReason: 'Last change:',
    help: 'Help with the form',
    helpTitle: 'Help with the form',
    helpText: 'Fill in every field marked with a star. You can save and come back later.',
    understood: 'Close the help',
  },
  sv: {
    about: 'Om tjänsten',
    aboutTitle: 'Om tjänsten',
    aboutText: 'Tjänsten drivs av kommunen och är öppen dygnet runt.',
    close: 'Stäng',
    changePhone: 'Ändra telefonnummer',
    changePhoneTitle: 'Ändra telefonnummer',
    changePhoneText: 'Vi skickar en kod med sms för att bekräfta det nya numret.',
    phoneNumber: 'Telefonnummer',
    save: 'Spara numret',
    keep: 'Behåll det gamla numret',
    stateOpen: 'Öppen',
    stateClosed: 'Stängd',
    lastReason: 'Senaste ändring:',
    help: 'Hjälp med formuläret',
    helpTitle: 'Hjälp med formuläret',
    helpText: 'Fyll i alla fält med stjärna. Du kan spara och komma tillbaka senare.',
    understood: 'Stäng hjälpen',
  },
})
