import { defineExampleTexts } from '../../components/local-example-texts.ts'

export const useFieldsetTexts = defineExampleTexts({
  en: {
    address: 'Postal address',
    street: 'Street address',
    postalCode: 'Postal code',
    city: 'City',
    addressHelpText: 'We send letters about your case to this address.',
    contactPerson: 'Name of your contact person',
    firstName: 'First name',
    lastName: 'Last name',
    nameQuestion: 'What is your name?',
    nameDescription: 'Write it as it is in your passport.',
    nameHelpText: 'Both names are needed to find your case.',
    nameError: 'Enter both your first and your last name.',
    send: 'Send application',
    lockedLegend: 'Applicant',
    lockedHelpText: 'The applicant can’t be changed after the application is sent.',
    applicant: 'Name of the applicant',
  },
  sv: {
    address: 'Postadress',
    street: 'Gatuadress',
    postalCode: 'Postnummer',
    city: 'Ort',
    addressHelpText: 'Vi skickar brev om ditt ärende till den här adressen.',
    contactPerson: 'Namn på din kontaktperson',
    firstName: 'Förnamn',
    lastName: 'Efternamn',
    nameQuestion: 'Vad heter du?',
    nameDescription: 'Skriv det som det står i ditt pass.',
    nameHelpText: 'Vi behöver båda namnen för att hitta ditt ärende.',
    nameError: 'Ange både ditt förnamn och ditt efternamn.',
    send: 'Skicka ansökan',
    lockedLegend: 'Sökande',
    lockedHelpText: 'Den sökande kan inte ändras när ansökan är skickad.',
    applicant: 'Den sökandes namn',
  },
})
