import { defineExampleTexts } from '../../components/local-example-texts.ts'

export const useToolbarTexts = defineExampleTexts({
  en: {
    formatting: 'Formatting',
    history: 'History',
    undo: 'Undo',
    redo: 'Redo',
    textStyle: 'Text style',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    insert: 'Insert',
    link: 'Link',
    image: 'Image',
    sampleText: 'Your application has been received.',
    guide: 'Read the guide',
    rowActions: 'Actions for the row',
    moveUp: 'Move up',
    moveDown: 'Move down',
    duplicate: 'Duplicate',
    remove: 'Delete',
    alignment: 'Alignment',
    alignStart: 'Align left',
    alignCenter: 'Centre',
    alignEnd: 'Align right',
    justify: 'Justify',
  },
  sv: {
    formatting: 'Formatering',
    history: 'Historik',
    undo: 'Ångra',
    redo: 'Gör om',
    textStyle: 'Textstil',
    bold: 'Fet',
    italic: 'Kursiv',
    underline: 'Understruken',
    insert: 'Infoga',
    link: 'Länk',
    image: 'Bild',
    sampleText: 'Din ansökan har tagits emot.',
    guide: 'Läs guiden',
    rowActions: 'Åtgärder för raden',
    moveUp: 'Flytta upp',
    moveDown: 'Flytta ned',
    duplicate: 'Duplicera',
    remove: 'Ta bort',
    alignment: 'Justering',
    alignStart: 'Vänsterjustera',
    alignCenter: 'Centrera',
    alignEnd: 'Högerjustera',
    justify: 'Marginaljustera',
  },
})
