import { defineExampleTexts } from '../../components/local-example-texts.ts'

export const useTableTexts = defineExampleTexts({
  en: {
    paymentsCaption: 'Housing allowance paid in 2026',
    month: 'Month',
    payoutDate: 'Payout date',
    amountPaid: 'Amount (SEK)',
    total: 'Total',
    january: 'January',
    february: 'February',
    march: 'March',
    casesCaption: 'Open cases',
    name: 'Name',
    caseNumber: 'Case number',
    amount: 'Amount (SEK)',
    handler: 'Handler',
    handlerLabel: 'Handler',
    decisionLabel: 'Decision',
    emptyCases: 'You have no open cases. New applications show up here when you send them.',
    allCases: 'All cases',
  },
  sv: {
    paymentsCaption: 'Utbetalt bostadsbidrag 2026',
    month: 'Månad',
    payoutDate: 'Utbetalningsdag',
    amountPaid: 'Belopp (kr)',
    total: 'Totalt',
    january: 'Januari',
    february: 'Februari',
    march: 'Mars',
    casesCaption: 'Öppna ärenden',
    name: 'Namn',
    caseNumber: 'Ärendenummer',
    amount: 'Belopp (kr)',
    handler: 'Handläggare',
    handlerLabel: 'Handläggare',
    decisionLabel: 'Beslut',
    emptyCases: 'Du har inga öppna ärenden. Nya ansökningar visas här när du har skickat dem.',
    allCases: 'Alla ärenden',
  },
})
