import { createThemeScriptSource } from '@kvirn-ui/core'
import type { ThemeScriptOptions } from '@kvirn-ui/core'
import { useSyncExternalStore } from 'react'

export interface KvirnThemeScriptProps {
  /** The CSP nonce for this response, for a strict `script-src`. */
  nonce?: string | undefined
  /**
   * The same object as `KvirnProvider theme`, so the defaults are written once. Only the three
   * defaults are read: `storage` (a function) can't cross from a Server Component and is ignored.
   */
  theme?: ThemeScriptOptions | undefined
}

const subscribeToNothing = () => () => {}
const isServerRender = () => true
const isClientRender = () => false

/**
 * A blocking inline script for `<head>` that sets `data-kv-color-scheme`,
 * `data-kv-contrast` and `data-kv-motion` on `<html>` before first paint, so there is no wrong-theme flash
 *. Reads `localStorage` only: with a custom storage adapter, render the
 * attributes on the server instead. Put `suppressHydrationWarning` on `<html>`.
 *
 * Render it in the server-rendered document only. Browsers never run scripts that React
 * creates on the client, so it renders nothing in a client render and stays in the
 * server markup through hydration.
 */
export function KvirnThemeScript({ nonce, theme }: KvirnThemeScriptProps) {
  const inServerMarkup = useSyncExternalStore(subscribeToNothing, isClientRender, isServerRender)
  if (!inServerMarkup) return null
  const source = createThemeScriptSource({
    defaultColorScheme: theme?.defaultColorScheme,
    defaultContrast: theme?.defaultContrast,
    defaultMotion: theme?.defaultMotion,
  })
  // The source is generated by core from constants and validated enums, never from input.
  return <script nonce={nonce} dangerouslySetInnerHTML={{ __html: source }} />
}
KvirnThemeScript.displayName = 'KvirnThemeScript'
