import { createThemeScriptSource } from '@kvirn-ui/core'
import type { ColorSchemePreference, ContrastPreference } from '@kvirn-ui/core'

export interface KvirnThemeScriptProps {
  /** The CSP nonce for this response, for a strict `script-src`. */
  nonce?: string | undefined
  /** Must match `KvirnProvider theme.defaultColorScheme`. Default `'system'`. */
  defaultColorScheme?: ColorSchemePreference | undefined
  /** Must match `KvirnProvider theme.defaultContrast`. Default `'system'`. */
  defaultContrast?: ContrastPreference | undefined
}

/**
 * A blocking inline script for `<head>` that sets `data-kv-color-scheme` and
 * `data-kv-contrast` on `<html>` before first paint, so there is no wrong-theme flash
 *. Reads `localStorage` only: with a custom storage adapter, render the
 * attributes on the server instead. Put `suppressHydrationWarning` on `<html>`.
 *
 * Render it in the server-rendered document only. Browsers never run scripts that React
 * creates on the client.
 */
export function KvirnThemeScript({
  nonce,
  defaultColorScheme,
  defaultContrast,
}: KvirnThemeScriptProps) {
  const source = createThemeScriptSource({ defaultColorScheme, defaultContrast })
  // The source is generated by core from constants and validated enums, never from input.
  return <script nonce={nonce} dangerouslySetInnerHTML={{ __html: source }} />
}
KvirnThemeScript.displayName = 'KvirnThemeScript'
