import { defineExampleTexts } from '../../components/local-example-texts.ts'

export const useCheckboxGroupTexts = defineExampleTexts({
  en: {
    legend: 'How should we contact you about your permit?',
    hint: 'Choose all that suit you. We only contact you about the decision.',
    email: 'Email',
    text: 'Text message',
    letter: 'Letter',
    emailHelp: 'The decision arrives within a week.',
    groupHelp: 'You can change this later under My pages.',
    youChose: 'You chose',
    nothing: 'nothing yet',
    send: 'Send',
    sent: 'Sent',
    errorMissing: 'Choose at least one way for us to contact you.',
    disabledLegend: 'Contact by letter or text message',
    disabledHelp: 'You can’t change this while your application is being processed.',
  },
  sv: {
    legend: 'Hur ska vi kontakta dig om tillståndet?',
    hint: 'Välj alla som passar. Vi kontaktar dig bara om beslutet.',
    email: 'E-post',
    text: 'Sms',
    letter: 'Brev',
    emailHelp: 'Beslutet kommer inom en vecka.',
    groupHelp: 'Du kan ändra dig senare under Mina sidor.',
    youChose: 'Du valde',
    nothing: 'inget ännu',
    send: 'Skicka',
    sent: 'Skickat',
    errorMissing: 'Välj minst ett sätt som vi kan kontakta dig på.',
    disabledLegend: 'Kontakt via brev eller sms',
    disabledHelp: 'Du kan inte ändra det medan din ansökan handläggs.',
  },
})
