import { defineExampleTexts } from '../../components/local-example-texts.ts'

export const useTabsTexts = defineExampleTexts({
  en: {
    list: 'Case',
    details: 'Details',
    documents: 'Documents',
    history: 'History',
    decision: 'Decision',
    detailsText: 'Building permit application for 4 Strand Road. The case awaits review.',
    documentsText: 'Drawings, a site plan and a control plan have arrived.',
    historyText:
      'The application arrived on 2 September. More information was requested on 9 September.',
    decisionText: 'The decision is not ready yet.',
    decisionReason: 'The decision tab opens when the case has been decided.',
    decisionLink: 'Read the decision',
    selected: 'Selected tab:',
    showHistory: 'Show history',
    sections: 'Application',
    applicant: 'Applicant',
    property: 'Property',
    attachments: 'Attachments',
    applicantText: 'Maria Lind, 4 Strand Road.',
    propertyText: 'Strand 1:23, 12 square metres of new building.',
    attachmentsText: 'Three files, 2.4 MB in total.',
  },
  sv: {
    list: 'Ärendet',
    details: 'Uppgifter',
    documents: 'Handlingar',
    history: 'Historik',
    decision: 'Beslut',
    detailsText: 'Ansökan om bygglov för Strandvägen 4. Ärendet väntar på granskning.',
    documentsText: 'Ritningar, situationsplan och kontrollplan har kommit in.',
    historyText: 'Ansökan kom in den 2 september. Komplettering begärdes den 9 september.',
    decisionText: 'Beslutet är inte klart än.',
    decisionReason: 'Fliken Beslut öppnas när ärendet har avgjorts.',
    decisionLink: 'Läs beslutet',
    selected: 'Vald flik:',
    showHistory: 'Visa historik',
    sections: 'Ansökan',
    applicant: 'Sökande',
    property: 'Fastighet',
    attachments: 'Bilagor',
    applicantText: 'Maria Lind, Strandvägen 4.',
    propertyText: 'Strand 1:23, 12 kvadratmeter ny byggnad.',
    attachmentsText: 'Tre filer, 2,4 MB tillsammans.',
  },
})
